name: Build and Deploy Site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Generate weekly summary from progress.csv
        run: |
          python scripts/build_weekly_summary.py
      - name: Generate Notes index
        run: |
          python scripts/build_notes_index.py
      - name: Generate References index from PDFs
        run: |
          python scripts/build_references_index.py
      - name: Build site
        run: |
          mkdocs build --strict
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
