
name: Weekly Summary (Scheduled)

on:
  schedule:
    - cron: "0 12 * * 0"  # 毎週日曜 21:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate weekly summary
        run: |
          python scripts/build_weekly_summary.py
      - name: Generate References index from PDFs
        run: |
          python scripts/build_references_index.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "docs/Progress Weekly Summary.md" "docs/references/index.md"
          git commit -m "chore: update weekly progress and references" || echo "No changes"
          git push
